version: "3.6"
services:
    db_level1:
        build: ./level1/db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            - MYSQL_ROOT_PASSWORD=45299417d8lo121f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    broken-auth-level1:
        build: ./level1/
        restart: unless-stopped
        ports:
            - 4001:80
        volumes:
            - ./level1/src:/var/www/html
        environment:
            # These password and stuff is not neccesarry too secret
            - MYSQL_HOSTNAME=db_level1
            - MYSQL_ROOT_PASSWORD=45299417d8lo121f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
    
    db_level2:
        build: ./level2/db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            - MYSQL_ROOT_PASSWORD=45299417d8lo121f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    broken-auth-level2:
        build: ./level2/
        restart: unless-stopped
        ports:
            - 4002:80
        volumes:
            - ./level2/src:/var/www/html
        environment:
            # These password and stuff is not neccesarry too secret
            - MYSQL_HOSTNAME=db_level2
            - MYSQL_ROOT_PASSWORD=45299417d8lo121f6a584d1488edb763
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
