version: "3.6"
services:
  typejuggling_level_1:
    build: .
    restart: unless-stopped
    ports:
      - "12001:80"
    volumes:
      - ./src:/var/www/html/
    environment:
    - FLAG=HPT{Still_pHP_tYPe_JUgGliNg}
