version: "3.6"
services:
  php-cmdi-3in1:
    build: .
    restart: unless-stopped
    ports:
      - "2001:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - FLAG_LEVEL1=VIS{Easy_RCE_wIth_CMDi}
      - FLAG_LEVEL2=VIS{iS_ThAT_FilTer_T0o_S!mple}
      - FLAG_LEVEL3=VIS{Many_More_wAys_t0_ExTend_A_Command}